{def $title_max = ezini('EditorInputSettings','MaxTitle','xrowmetadata.ini')
     $descr_max = ezini('EditorInputSettings','MaxDescription','xrowmetadata.ini')
     $hide_keywords = ezini('EditorInputSettings', 'HideKeywords', 'xrowmetadata.ini')|eq('enabled')
}

{literal}
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery('#more_checkbox').click(function() {
                jQuery('#options_div').toggle();
            });
            
        });
    </script>
{/literal}

{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="block">
    <label>{'Title'|i18n( 'design/standard/class/datatype' )}:</label>
    <input data-maxlength={$title_max} id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute'
    )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_title" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[title]" size="100" maxsize="255" value="{$attribute.content.title|wash()}" />
</div>

<div class="block">
    <label>{'Description'|i18n( 'design/standard/class/datatype' )}:</label>
    <input data-maxlength="{$descr_max}" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute'
    )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_description" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[description]" size="100" maxsize="255" value="{$attribute.content.description|wash()}" />
</div>

{* HideKeywords ini setting controls whether to show keywords inside the options block or before it *}
{set-block variable=$keywords}
    <label>{'Keywords'|i18n( 'design/standard/class/datatype' )}:</label>
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_keywords" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[keywords]" size="100" maxsize="1055" value="{$attribute.content.keywords|implode( ', ' )|wash()}" />
{/set-block}

{if not($hide_keywords)}
<div class="block">
    {$keywords}
</div>
{/if}

<div class="block">

    <div class="element"> 
        <label><input id="more_checkbox" type="checkbox" {if or(ne($attribute.content.sitemap_use,1),ne($attribute.content.change,'daily'),ne($attribute.content.priority,''))}checked="checked"{/if} /> {'More options'|i18n( 'design/standard/class/datatype' )}</label>
    </div>

    <div id="options_div" {if and(eq($attribute.content.sitemap_use,1),eq($attribute.content.change,'daily'),eq($attribute.content.priority,''))}class="hide"{/if}>
        
        <div class="element"> 
            <label>{'Use in sitemap'|i18n( 'design/standard/class/datatype' )}:</label>
            <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_keywords" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[sitemap_use]" size="1">
            <option value="0" {if ne($attribute.content.sitemap_use,'1')}selected{/if}>{'no'|i18n( 'design/standard/class/datatype' )}</option>
            <option value="1" {if eq($attribute.content.sitemap_use,'1')}selected{/if}>{'yes'|i18n( 'design/standard/class/datatype' )}</option>
            </select>
        </div>
        
        <div class="element">
            <label>{'Change frequence'|i18n( 'design/standard/class/datatype' )}:</label>
            <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_keywords" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[change]" size="1">
                <option value="always" {if eq($attribute.content.change,'always')}selected{/if}>{'always'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="hourly" {if eq($attribute.content.change,'hourly')}selected{/if}>{'hourly'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="daily" {if eq($attribute.content.change,'daily')}selected{/if}>{'daily'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="weekly" {if eq($attribute.content.change,'weekly')}selected{/if}>{'weekly'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="monthly" {if eq($attribute.content.change,'monthly')}selected{/if}>{'monthly'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="yearly" {if eq($attribute.content.change,'yearly')}selected{/if}>{'yearly'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="never" {if eq($attribute.content.change,'never')}selected{/if}>{'never'|i18n( 'design/standard/class/datatype' )}</option>
            </select>
        </div>
        
        <div class="element">
            <label>{'Priority'|i18n( 'design/standard/class/datatype' )}:</label>
            <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_keywords" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[priority]" size="1">
                <option value="" {if eq($attribute.content.priority,'')}selected{/if}>{'automatic'|i18n( 'design/standard/class/datatype' )}</option>
                <option value="0.0" {if eq($attribute.content.priority,'0.0')}selected{/if}>0.0</option>
                <option value="0.1" {if eq($attribute.content.priority,'0.1')}selected{/if}>0.1</option>
                <option value="0.2" {if eq($attribute.content.priority,'0.2')}selected{/if}>0.2</option>
                <option value="0.3" {if eq($attribute.content.priority,'0.3')}selected{/if}>0.3</option>
                <option value="0.4" {if eq($attribute.content.priority,'0.4')}selected{/if}>0.4</option>
                <option value="0.5" {if eq($attribute.content.priority,'0.5')}selected{/if}>0.5</option>
                <option value="0.6" {if eq($attribute.content.priority,'0.6')}selected{/if}>0.6</option>
                <option value="0.7" {if eq($attribute.content.priority,'0.7')}selected{/if}>0.7</option>
                <option value="0.8" {if eq($attribute.content.priority,'0.8')}selected{/if}>0.8</option>
                <option value="0.9" {if eq($attribute.content.priority,'0.9')}selected{/if}>0.9</option>
                <option value="1.0" {if eq($attribute.content.priority,'1.0')}selected{/if}>1.0</option>
            </select>
        </div>
        {if $hide_keywords}
        <div class="element">
            {$keywords}
        </div>
        {/if}

        <div class="element">
            <label>{'Canonical Link (starts with protocol https)'|i18n( 'design/standard/class/datatype' )}:</label>
            <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_keywords" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="url" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[canonical_url]" size="100" maxsize="1055" value="{$attribute.content.canonical_url|wash()}" />
        </div>

        {def $mt_og_object = false()}
        {if and($attribute.data_int, $attribute.data_int|gt(0))}
            {set $mt_og_object = fetch('content','object',hash('id',$attribute.data_int))}
        {/if}
        {def $mt_image_attr = false()}
        {def $mt_image_path = ''}
        {if $mt_og_object}
            {if $mt_og_object.data_map.site_opengraph_image}{set $mt_image_attr = $mt_og_object.data_map.site_opengraph_image}{/if}
            {if and(not($mt_image_attr), $mt_og_object.data_map.image)}{set $mt_image_attr = $mt_og_object.data_map.image}{/if}
            {if and(not($mt_image_attr), $mt_og_object.data_map.site_logo)}{set $mt_image_attr = $mt_og_object.data_map.site_logo}{/if}
            {if and(not($mt_image_attr), $mt_og_object.data_map.file)}{set $mt_image_attr = $mt_og_object.data_map.file}{/if}
            {if $mt_image_attr}
                {if eq($mt_image_attr.data_type_string, 'ezimage')}
                    {set $mt_image_path = $mt_image_attr.content.original.full_path}
                {elseif eq($mt_image_attr.data_type_string, 'ezbinaryfile')}
                    {set $mt_image_path = $mt_image_attr.content.filepath}
                {/if}
            {/if}
        {/if}
        <div class="element" id="ezobjectrelation_browse_{$attribute.id}">
            <label>{'Open Graph image'|i18n( 'design/standard/class/datatype' )}:</label>
            <table class="list" cellspacing="0">
            <thead>
            <tr>
                <th>{'Name'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Type'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Section'|i18n( 'design/standard/content/datatype' )}</th>
                <th>{'Published'|i18n( 'design/standard/content/datatype' )}</th>
            </tr>
            </thead>
            <tbody>
            <tr class="bglight">
            {if $mt_og_object}
                <td>
                    {$mt_og_object.name|wash()}
                    {if $mt_image_path|ne('')}
                        <br /><img src="{concat('/', $mt_image_path)}" alt="{$mt_og_object.name|wash()}" style="max-width:200px; max-height:100px;" />
                    {/if}
                </td>
                <td>{if $mt_image_attr}{$mt_image_attr.data_type_string|wash()}{else}{$mt_og_object.class_name|wash()}{/if}</td>
                <td>{fetch(section, object, hash(section_id, $mt_og_object.section_id)).name|wash}</td>
                <td>{if $mt_og_object.status|ne(1)}{'No'|i18n( 'design/standard/content/datatype' )}{else}{'Yes'|i18n( 'design/standard/content/datatype' )}{/if}</td>
            {else}
                <td>--name--</td>
                <td>--class-name--</td>
                <td>--section-name--</td>
                <td>--published--</td>
            {/if}
            </tr>
            </tbody>
            </table>
            {if not($mt_og_object)}
                <p class="ezobject-relation-no-relation">{'There are no related object.'|i18n( 'design/standard/content/datatype' )}</p>
            {/if}
            <input type="hidden" name="{$attribute_base}_data_object_relation_id_{$attribute.id}" value="{$attribute.data_int|wash()}" />
            {if $mt_og_object}
                <input class="button ezobject-relation-remove-button" type="submit" name="CustomActionButton[{$attribute.id}_remove_object]" value="{'Remove object'|i18n( 'design/standard/content/datatype' )}" />
            {else}
                <input class="button ezobject-relation-add-button" type="submit" name="CustomActionButton[{$attribute.id}_browse_object]" value="{'Add an existing object'|i18n( 'design/standard/content/datatype' )}" title="{'Browse to add an existing object in this relation'|i18n( 'design/standard/content/datatype' )}" />
            {/if}
        </div>
        <div class="element">
            <label>{'Open Graph image width'|i18n( 'design/standard/class/datatype' )}:</label>
            <input class="box" type="number" min="0" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[og_image_width]" size="10" value="{$attribute.content.og_image_width|wash()}" />
        </div>
        <div class="element">
            <label>{'Open Graph image height'|i18n( 'design/standard/class/datatype' )}:</label>
            <input class="box" type="number" min="0" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[og_image_height]" size="10" value="{$attribute.content.og_image_height|wash()}" />
        </div>
        <div class="element">
            <label>{'Open Graph image alt'|i18n( 'design/standard/class/datatype' )}:</label>
            <input class="box" type="text" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[og_image_alt]" size="100" value="{$attribute.content.og_image_alt|wash()}" />
        </div>
        <div class="element">
            <label>{'Open Graph image type'|i18n( 'design/standard/class/datatype' )}:</label>
            <input class="box" type="text" name="{$attribute_base}_xrowmetadata_data_array_{$attribute.id}[og_image_type]" size="100" value="{$attribute.content.og_image_type|wash()}" />
        </div>
    </div>

</div>
